### ISSUE TITLE
Score tracking

### ISSUE THREAD

**Issue by CubePresser** [OSU-CS492-W19/final-project-team-15#5]
Keep total score for current session (Multiple guessing rounds).

- [x] UI visual that displays score (Probably top right or left of screen)
- [x] Add score obtained from current guess to total score value
- [x] Update UI on score change
